### ISSUE TITLE
Need a way to sink overlay with prediction result as rtsp out for AI 

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#17]
we are facing lot of design challenges with LVA to get and show the results overlayed, 

- Full image needs to be sent to the AI module even if the model can take a smaller image to enable the display
- Encoding and decoding of the image take compute to delay pipeline for ai processing 
- no clear sample to do this easily ,..
can LVA provide a way to do overlay results as rtsp out so AI module can focus on getting AI results 

sampel is below 
![image](https://user-images.githubusercontent.com/21267354/93920800-88f88780-fcc4-11ea-823b-28c7a612a21f.png)

**Comment by mustafakasap** [comment]
Can you provide more details?
- LVA sends frames to lvaExtension (your AI module) according to the topology manifest that you specify. Inside that topology file you can ask LVA to send frames in:
- Specific size (so it will send frames in any dimension your want)
- specify aspect ratio (so i.e. if original camera resolution is HD but you ask LVA to send frames in 200px by 300px size, you can specify different aspect ratio parameters to LVA by i.e. telling make padding (letterbox) or i.e. keep aspect ratio etc.)
- you can also tell LVA to send you images in jpg, png like encoded format, or you can even tell LVA to send RAW frames (decoded), so you dont need to decode them but use as is as byte arrays...

all above and more can be specified in the topology file.

**Comment by initmahesh** [comment]
thanks this really useful, 
how can we send row frames, what format you recommend for that?

Can we get overlayed results as rtsp sink is the ask, as otherwise we cannot reduce the size of the image for inference as the same image cannot be used for display (display will need in good resolution and full size)
