### ISSUE TITLE
How can we pick more images from buffer og gRPC wihtout sendign back result for first buffer

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#20]
We need to do a parallel process 
preprocess while we are running inference in our module 

## 2. also, another question here is : 
#create gRPC server and start running
server = grpc.server(futures.ThreadPoolExecutor(max_workers=3))
if we have n camera streams, what’s the recommended max_workers

**Comment by mustafakasap** [comment]
1) you can use grpc ASYNC API for asynchronous read and write threads independently running. https://grpc.github.io/grpc/python/grpc_asyncio.html

2) Setting the write value for Number of worker depends have direct relation with your scenario, workload, compute power. If you have multi-core processor and want to handle high fps workload, you can increase the workers (multiple threads).

**Comment by initmahesh** [comment]
How can we change this on LVA as all the user is allowed to select the gRPC to HTTP option and if they select gRPC we have to return the result from first read before we can read the buffer again, can we please guidance or sample on how above can be achieved with lva ..

**Comment by initmahesh** [comment]
here is what we are expecting in new sample 
- the ai module should be able to read batch fo frames from LVA eg 5 frames
- can run ai on frame 1 and if even 1 out of 5 frames are acked we will be allowed to read another batch of 5 

this will ensure that ai module always have frames to process and not wait until the next frames are being read
