### ISSUE TITLE
Need a sample for ai module that does multiple processing for multiple cameras

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#21]
The current LVA sample does serial processing for frames across many cameras this makes it impossible for us to support more than 3 cameras at 8 fps with gRPC on T4 gpu running a very small tiny yolo network(30ms to pre,post-process _ ai run) 

need a sample from LVA that scale the ai module to run parallel processing as no. of camera increase 
- we can scale on 1 GPU 
- we can scale on more GPU on same machine

**Comment by mustafakasap** [comment]
Thanks for your message.

Can you please write the steps to re-produce the issue, so we can follow the same steps to debug?

if there is no issue but this is just a feedback, feature request etc. please use the amslvapm@microsoft.com email address for your feedback and feature requests.

**Comment by initmahesh** [comment]
you can deploy our solution and follow video here to reproduce just add 10 camera and try switching, as you g o more then 4 cameras you will see the issue on gRPC path ..
https://github.com/Azure-Samples/azure-intelligent-edge-patterns/tree/yadavm_factoryai/factory-ai-vision

**Comment by mustafakasap** [comment]
Please see answer to second question in https://github.com/Azure-Samples/live-video-analytics-iot-edge-python/issues/20 

Did you tried increasing the number of worker roles?
