### ISSUE TITLE
runing row LVA with 5 video can take all the CPU on a Xeon machine 

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#22]
In this setup on ai module we returned every frame back with dummy json to check what can LVA support on our CPU 
![image](https://user-images.githubusercontent.com/21267354/93926338-3622ce00-fccc-11ea-8fa0-5e4ab7becbf7.png)

how to repro 

![image](https://user-images.githubusercontent.com/21267354/93926411-50f54280-fccc-11ea-98fe-0c04994d4cb6.png)

**Comment by mustafakasap** [comment]
Can you elaborate more about your question? you wrote you want to check what can LVA support on your CPU? Cant you see what LVA support on your CPU? isn't the first screen shot already shows what LVA supports on your CPU?

Thanks,

**Comment by initmahesh** [comment]
clarification :: 
we are processing multiple camera`s if we can only support 5 camera`s processing on a Xeon processor then we need to publish that on documentation as our customers to make an informed decision,

so the ask here from team lva is 
- publish no. of camera supported with live display on Azure Stack Edge or any other hardware

**Comment by naiteeks** [comment]
closing this as this marked as a question now.
