### ISSUE TITLE
need kubernetes support on LVA to scale beyond 10 cameras at 30 fps

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#23]
as we have observed the cpu capacity becomes a bottleneck for scenario where we use more then 10 cameras, it will great if we can scale lva module to a cluster across many cpu`s.

**Comment by initmahesh** [comment]
Iot edge is one node

**Comment by mustafakasap** [comment]
Thanks for your message. 

Can you please write the steps to re-produce the issue, so we can follow the same steps to debug? 

if there is no issue but this is just a feedback, feature request etc. please use the amslvapm@microsoft.com email address for your feedback and feature requests.
